apiVersion: v1
kind: Service
metadata:
  name: pr-audit-ui-service
  namespace: pr-audit
spec:
  type: ClusterIP
  selector:
    app: pr-audit-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
